# Site settings
title: Kittens step
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Nadun
baseurl: 
url: "" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
paginate: 3
google_analytics: 'UA-XXXXXXX-X'
